apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-bmg-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-bmg-back
  template:
    metadata:
      labels:
        app: azure-bmg-back
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-bmg-back
        image: akstutorialacrgeorge.azurecr.io/azure-bmg-back:v3
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 8000
          name: bmg-backend
---
apiVersion: v1
kind: Service
metadata:
  name: azure-bmg-back
spec:
  ports:
  - port: 9000
    targetPort: 8000
  selector:
    app: azure-bmg-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-bmg-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-bmg-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-bmg-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-bmg-front
        image: akstutorialacrgeorge.azurecr.io/azure-bmg-front:v9
        ports:
        - containerPort: 3000 
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: BACKEND
          value: "azure-bmg-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-bmg-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: azure-bmg-front
